#!/usr/bin/env bash
set -euo pipefail

ORIGIN='https://POOL_HOST'
API_KEY='API_KEY'
MODEL='gpt-5.6-sol'
PROVIDER_ID="poolserver"

say() { printf '%s\n' "$*"; }

CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"
CONFIG="$CODEX_HOME/config.toml"
mkdir -p "$CODEX_HOME"
umask 077

if [ -L "$CONFIG" ]; then
  say "Refusing to replace a symlinked Codex config file."
  exit 1
fi

CONFIG_TMP="$(mktemp "$CODEX_HOME/.config.toml.tmp.XXXXXX")"
cleanup() { rm -f "$CONFIG_TMP"; }
trap cleanup EXIT

if [ -f "$CONFIG" ]; then
  BAK="$CONFIG.bak.$(date +%Y%m%d%H%M%S).$$"
  cp "$CONFIG" "$BAK"
  say "已备份原有配置 -> $BAK"
fi

cat > "$CONFIG_TMP" <<EOF
# Generated by Pool — points the Codex CLI at this pool.
model = "$MODEL"
model_provider = "$PROVIDER_ID"
model_reasoning_effort = "ultra"
approval_policy = "never"
sandbox_mode = "danger-full-access"

EOF

if [ -f "$CONFIG" ]; then
  awk -v provider="$PROVIDER_ID" -v managed_root_keys='model|model_provider|model_reasoning_effort|approval_policy|sandbox_mode' '
    BEGIN { section=""; skip=0; features_seen=0; goals_written=0 }
    function ensure_goal() {
      if (section == "[features]" && !goals_written) {
        print "goals = true"
        goals_written=1
      }
    }
    /^\[/ {
      ensure_goal()
      section=$0
      skip=0
      if ($0 == "[model_providers." provider "]" ||
          index($0, "[model_providers." provider ".") == 1) { skip=1; next }
      if ($0 == "[features]") { features_seen=1 }
    }
    skip { next }
    section == "[features]" && $0 ~ /^[[:space:]]*goals[[:space:]]*=/ {
      if (!goals_written) print "goals = true"
      goals_written=1
      next
    }
    section == "" && $0 ~ ("^(" managed_root_keys ")[[:space:]]*=") { next }
    { print }
    END {
      ensure_goal()
      if (!features_seen) {
        print ""
        print "[features]"
        print "goals = true"
      }
    }
  ' "$CONFIG" >> "$CONFIG_TMP"
else
  cat >> "$CONFIG_TMP" <<EOF

[features]
goals = true
EOF
fi

cat >> "$CONFIG_TMP" <<EOF
[model_providers.$PROVIDER_ID]
name = "OpenAI"
base_url = "$ORIGIN/v1"
wire_api = "responses"
requires_openai_auth = false
experimental_bearer_token = "$API_KEY"
EOF

mv "$CONFIG_TMP" "$CONFIG"
trap - EXIT
say "已写入 $CONFIG"
say "已配置 Goal、模型、推理强度、沙箱审批、URL 与 API key"
say "model=$MODEL"
