package api

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"

	"codex-account-pool/internal/anthropicwire"
	"codex-account-pool/internal/cloak"
	"codex-account-pool/internal/identity"
	"codex-account-pool/internal/storage"
)

const claudeCodeProbeIdentityLine = "You are a Claude agent, built on Anthropic's Claude Agent SDK."

// ensureClaudeCodeIdentityBody normalizes an arbitrary Anthropic Messages body into
// the body family claimed by the custom-provider claude-cli headers. Existing billing
// and identity blocks are moved to their native leading positions without changing the
// relative order of the caller's other system content; missing identity is inserted.
func ensureClaudeCodeIdentityBody(raw []byte) []byte {
	decoder := json.NewDecoder(bytes.NewReader(raw))
	decoder.UseNumber()
	var root map[string]interface{}
	if err := decoder.Decode(&root); err != nil {
		return raw
	}

	identityBlock := func() map[string]interface{} {
		return map[string]interface{}{
			"type": "text", "text": claudeCodeProbeIdentityLine,
			"cache_control": map[string]interface{}{"type": "ephemeral"},
		}
	}
	switch system := root["system"].(type) {
	case nil:
		root["system"] = []interface{}{identityBlock()}
	case string:
		trimmed := strings.TrimSpace(system)
		if !strings.HasPrefix(trimmed, claudeCodeProbeIdentityLine) &&
			!strings.HasPrefix(trimmed, "You are Claude Code, Anthropic's official CLI for Claude.") {
			root["system"] = []interface{}{identityBlock(), map[string]interface{}{"type": "text", "text": system}}
		}
	case []interface{}:
		var billing interface{}
		var identityBlockValue interface{}
		rest := make([]interface{}, 0, len(system))
		for _, value := range system {
			block, _ := value.(map[string]interface{})
			text, _ := block["text"].(string)
			trimmed := strings.TrimSpace(text)
			switch {
			case strings.HasPrefix(trimmed, "x-anthropic-billing-header:"):
				if billing == nil {
					billing = value
				}
			case strings.HasPrefix(trimmed, claudeCodeProbeIdentityLine),
				strings.HasPrefix(trimmed, "You are Claude Code, Anthropic's official CLI for Claude."):
				if identityBlockValue == nil {
					identityBlockValue = value
				}
			default:
				rest = append(rest, value)
			}
		}
		if identityBlockValue == nil {
			identityBlockValue = identityBlock()
		}
		normalized := make([]interface{}, 0, len(rest)+2)
		if billing != nil {
			normalized = append(normalized, billing)
		}
		normalized = append(normalized, identityBlockValue)
		root["system"] = append(normalized, rest...)
	default:
		return raw
	}

	if normalized, err := anthropicwire.MarshalPreservingOrder(raw, root); err == nil {
		return normalized
	}
	return raw
}

// claudeCodeMinimalProbeBody builds internally-generated health/discovery probes with
// the same body identity and JSON wire shape as the claude-cli headers and Bun
// transport used to send them. Without this, low-frequency background/admin calls
// exposed a stable Go map-key order and omitted the billing, device and session fields
// carried by the client identity they claimed to be.
func (s *Server) claudeCodeMinimalProbeBody(
	account storage.Account,
	token storage.AccountToken,
	egress storage.EgressProfile,
	model string,
	promptText string,
	maxTokens int,
) ([]byte, string) {
	root := map[string]interface{}{
		"model": model,
		"messages": []interface{}{map[string]interface{}{
			"role": "user", "content": promptText,
		}},
		"system": []interface{}{map[string]interface{}{
			"type": "text", "text": claudeCodeProbeIdentityLine,
			"cache_control": map[string]interface{}{"type": "ephemeral"},
		}},
		"tools":      []interface{}{},
		"max_tokens": maxTokens,
		"stream":     false,
	}
	raw, err := anthropicwire.MarshalPreservingOrder(nil, root)
	if err != nil {
		// Every value above is a JSON primitive/container, so this is only a
		// defensive fallback. Keep it valid and let the regular error response
		// classify the probe rather than panic in an administrative path.
		raw = []byte(`{"model":"claude","messages":[],"max_tokens":1,"stream":false}`)
	}
	osHint := s.osHint(raw, egress)
	id := identity.ForOS(s.identitySecret(), account.ID, osHint)
	billingVersion := s.cfg.ClaudeCLIVersionOrDefault(id.ClaudeCLIVersion)
	// These probes are generated by the server's programmatic SDK-style path, so
	// seed sdk-cli before virtualization. Virtualize replaces the version/build
	// while preserving the genuine entrypoint, keeping body billing and UA aligned.
	system, _ := root["system"].([]interface{})
	root["system"] = append([]interface{}{map[string]interface{}{
		"type": "text",
		"text": fmt.Sprintf(
			"x-anthropic-billing-header: cc_version=%s.%s; cc_entrypoint=sdk-cli;",
			billingVersion,
			identity.ClaudeCodeBuild,
		),
	}}, system...)
	if shapedRaw, marshalErr := anthropicwire.MarshalPreservingOrder(nil, root); marshalErr == nil {
		raw = shapedRaw
	}
	shaped := cloak.VirtualizeClaudeCode(raw, id, s.cfg.SensitiveWordsFor("claude"), claudeIsOAuth(token), billingVersion)
	return shaped.Body, osHint
}
