package api

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
	"strconv"
	"strings"
	"sync"
	"time"
)

type codexCacheKeyMetric struct {
	minute int64
	rpm    int64
	active int64
	peak   int64
}

type codexCacheKeyObservation struct {
	Hash            string
	Shard           int
	MinuteRPM       int64
	ConcurrencyPeak int64
	done            func()
	doneOnce        *sync.Once
}

func (o *codexCacheKeyObservation) Done() {
	// The observation is commonly deferred and may also be closed by a transport
	// fallback; make the decrement idempotent so a retry cannot undercount active
	// concurrency for a different request.
	if o.doneOnce == nil {
		if o.done != nil {
			o.done()
		}
		return
	}
	o.doneOnce.Do(func() {
		if o.done != nil {
			o.done()
		}
	})
}

func (s *Server) observeCodexPromptCacheKey(accountID, model, key string, shardCount int, now time.Time) codexCacheKeyObservation {
	key = strings.TrimSpace(key)
	if key == "" {
		return codexCacheKeyObservation{Shard: -1}
	}
	mac := hmac.New(sha256.New, s.identitySecret())
	_, _ = mac.Write([]byte("codex-prompt-cache-key\x00" + strings.TrimSpace(accountID) + "\x00" + strings.TrimSpace(model) + "\x00" + key))
	metricKey := hex.EncodeToString(mac.Sum(nil))
	minute := now.Unix() / 60
	s.codexCacheMetricsMu.Lock()
	if s.codexCacheMetrics == nil {
		s.codexCacheMetrics = make(map[string]*codexCacheKeyMetric)
	}
	metric := s.codexCacheMetrics[metricKey]
	if metric == nil {
		metric = &codexCacheKeyMetric{minute: minute}
		s.codexCacheMetrics[metricKey] = metric
	}
	if metric.minute != minute {
		metric.minute = minute
		metric.rpm = 0
		metric.peak = metric.active
	}
	metric.rpm++
	metric.active++
	if metric.active > metric.peak {
		metric.peak = metric.active
	}
	rpm, peak := metric.rpm, metric.peak
	if len(s.codexCacheMetrics) > 8192 {
		for hash, candidate := range s.codexCacheMetrics {
			if candidate.active == 0 && candidate.minute < minute-1 {
				delete(s.codexCacheMetrics, hash)
			}
		}
	}
	s.codexCacheMetricsMu.Unlock()

	return codexCacheKeyObservation{
		Hash:            metricKey[:16],
		Shard:           codexPromptCacheKeyShardFromKey(key, shardCount),
		MinuteRPM:       rpm,
		ConcurrencyPeak: peak,
		doneOnce:        &sync.Once{},
		done: func() {
			s.codexCacheMetricsMu.Lock()
			if current := s.codexCacheMetrics[metricKey]; current != nil && current.active > 0 {
				current.active--
			}
			s.codexCacheMetricsMu.Unlock()
		},
	}
}

func codexPromptCacheKeyShardFromKey(key string, shardCount int) int {
	// Only keys generated by the relay carry the `_sNN` suffix. An operator's
	// explicit key is opaque—even if it happens to contain the same characters.
	if !codexGeneratedPromptCacheKey(key) {
		return -1
	}
	if marker := strings.LastIndex(key, "_s"); marker >= 0 && marker+2 < len(key) {
		if marker+4 == len(key) {
			if shard, err := strconv.Atoi(key[marker+2:]); err == nil && shard >= 0 && shard < 16 {
				return shard
			}
		}
	}
	if shardCount == 1 && strings.HasPrefix(key, "auto_") {
		return 0
	}
	return -1
}

func codexGeneratedPromptCacheKey(key string) bool {
	key = strings.TrimSpace(key)
	if !strings.HasPrefix(key, "auto_") {
		return false
	}
	body := strings.TrimPrefix(key, "auto_")
	if len(body) == 24 {
		return isLowerHex(body)
	}
	if len(body) != 28 || body[24:26] != "_s" {
		return false
	}
	return isLowerHex(body[:24]) && body[26] >= '0' && body[26] <= '9' && body[27] >= '0' && body[27] <= '9'
}

func isLowerHex(value string) bool {
	for _, c := range value {
		if !((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f')) {
			return false
		}
	}
	return true
}
