package api

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// TestSetupScriptBashSyntaxAndContents guards the one-click setup script generated by
// buildCodexConfigScript: it must configure BOTH Codex (config.toml) and Claude Code
// (ANTHROPIC_* env), wire rtk, and — critically — be valid bash (the embedded python
// heredoc + if/then/else blocks are easy to break).
func TestSetupScriptBashSyntaxAndContents(t *testing.T) {
	script := buildCodexConfigScript("https://pool.example/", "cap_abc123", "gpt-5.5", "xhigh", "never", "danger-full-access")
	for _, want := range []string{
		"config.toml",          // Codex
		"ANTHROPIC_BASE_URL",   // Claude Code
		"ANTHROPIC_AUTH_TOKEN", // Claude Code
		".claude/settings.json",
		"rtk init",        // downstream rtk
		"POOL_SKIP_RTK",   // opt-out
		`MODEL='gpt-5.5'`, // model via shell var → config.toml
		`model_reasoning_effort = "xhigh"`,
		`approval_policy = "never"`,           // auto-approve all
		`sandbox_mode = "danger-full-access"`, // full permissions (goal mode)
	} {
		if !strings.Contains(script, want) {
			t.Fatalf("setup script missing %q", want)
		}
	}
	// Blanked-out behavior values must be omitted from the TOML (operator can dial
	// back). The help-text echoes still mention the words, so check the assignment form.
	bare := buildCodexConfigScript("https://pool.example/", "cap_abc123", "gpt-5.5", "", "", "")
	for _, line := range []string{`approval_policy = "`, `sandbox_mode = "`, `model_reasoning_effort = "`} {
		if strings.Contains(bare, line) {
			t.Fatalf("empty behavior values should omit %q from config", line)
		}
	}
	if _, err := exec.LookPath("bash"); err != nil {
		t.Skip("bash not available")
	}
	p := filepath.Join(t.TempDir(), "setup.sh")
	if err := os.WriteFile(p, []byte(script), 0o600); err != nil {
		t.Fatal(err)
	}
	if out, err := exec.Command("bash", "-n", p).CombinedOutput(); err != nil {
		t.Fatalf("generated setup script has bash syntax errors: %v\n%s", err, out)
	}
}

func TestSetupScriptSanitizesModel(t *testing.T) {
	script := buildCodexConfigScript("https://pool.example/", "cap_abc123", "gpt-5\"\nmalicious = true", "", "", "")
	if strings.Contains(script, "MODEL=\"gpt-5\"\nmalicious") || strings.Contains(script, "\nmalicious = true") {
		t.Fatalf("model value was not sanitized:\n%s", script)
	}
	if !strings.Contains(script, `MODEL='gpt-5malicious = true'`) {
		t.Fatalf("sanitized model assignment missing:\n%s", script)
	}
	script = buildCodexConfigScript("https://pool.example/$(touch bad)", "cap_abc123", "gpt-5`touch bad`", "", "", "")
	if strings.Contains(script, "ORIGIN=\"") || strings.Contains(script, "MODEL=\"") {
		t.Fatalf("shell assignments must use single-quoted literals:\n%s", script)
	}
}
