package api

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// TestSetupScriptBashSyntaxAndContents guards the one-click setup script generated by
// buildCodexConfigScript: it must offer the client/RTK choices, keep Codex and Claude
// configuration separated, wire Claude through gateway run-claude, and be valid bash.
func TestSetupScriptBashSyntaxAndContents(t *testing.T) {
	script := buildCodexConfigScript("https://pool.example/", "cap_abc123", "gpt-5.5", "xhigh", "never", "danger-full-access")
	for _, want := range []string{
		"POOL_CLIENT",       // automation override
		"POOL_INSTALL_RTK",  // automation override
		"POOL_STRICT_LINUX", // Claude strict default
		"select_client",
		"configure_codex",
		"configure_claude",
		"gateway run-claude --",
		"CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC",
		"DISABLE_AUTOUPDATER",
		"rtk init --codex",
		`MODEL='gpt-5.5'`, // model via shell var → config.toml
		`model_reasoning_effort = "xhigh"`,
		`approval_policy = "never"`,           // auto-approve all
		`sandbox_mode = "danger-full-access"`, // full permissions (goal mode)
	} {
		if !strings.Contains(script, want) {
			t.Fatalf("setup script missing %q", want)
		}
	}
	// Blanked-out behavior values must be omitted from the TOML (operator can dial
	// back). The help-text echoes still mention the words, so check the assignment form.
	bare := buildCodexConfigScript("https://pool.example/", "cap_abc123", "gpt-5.5", "", "", "")
	for _, line := range []string{`approval_policy = "`, `sandbox_mode = "`, `model_reasoning_effort = "`} {
		if strings.Contains(bare, line) {
			t.Fatalf("empty behavior values should omit %q from config", line)
		}
	}
	if _, err := exec.LookPath("bash"); err != nil {
		t.Skip("bash not available")
	}
	p := filepath.Join(t.TempDir(), "setup.sh")
	if err := os.WriteFile(p, []byte(script), 0o600); err != nil {
		t.Fatal(err)
	}
	if out, err := exec.Command("bash", "-n", p).CombinedOutput(); err != nil {
		t.Fatalf("generated setup script has bash syntax errors: %v\n%s", err, out)
	}
}

func TestSetupScriptCodexBranchIsIsolatedFromClaudeGateway(t *testing.T) {
	script := buildCodexConfigScript("https://pool.example/", "cap_abc123", "gpt-5.5", "", "", "")

	codexBranch := scriptBetween(t, script, "configure_codex() {", "\n}\n\nconfigure_claude()")
	for _, want := range []string{
		`CONFIG="$CODEX_HOME/config.toml"`,
		`base_url = "$ORIGIN/v1"`,
		`wire_api = "responses"`,
		`experimental_bearer_token`,
		`rtk init --codex`,
	} {
		if !strings.Contains(codexBranch, want) {
			t.Fatalf("codex branch missing %q\n---\n%s", want, codexBranch)
		}
	}
	for _, forbidden := range []string{
		"gateway run-claude",
		".claude/settings.json",
		"ANTHROPIC_BASE_URL",
		"install-wrapper",
	} {
		if strings.Contains(codexBranch, forbidden) {
			t.Fatalf("codex branch must not contain %q\n---\n%s", forbidden, codexBranch)
		}
	}
}

func TestSetupScriptClaudeBranchUsesGatewayStrictRuntime(t *testing.T) {
	script := buildCodexConfigScript("https://pool.example/", "cap_abc123", "gpt-5.5", "", "", "")

	claudeBranch := scriptBetween(t, script, "configure_claude() {", "\n}\n\nmain()")
	for _, want := range []string{
		"install_gateway_binary",
		`gateway init --pool-url "$ORIGIN" --key "$API_KEY"`,
		"gateway probe-identity",
		"gateway run-claude --",
		`POOL_STRICT_LINUX="${POOL_STRICT_LINUX:-1}"`,
		"CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1",
		"DO_NOT_TRACK=1",
		"DISABLE_TELEMETRY=1",
		"DISABLE_ERROR_REPORTING=1",
		"DISABLE_AUTOUPDATER=1",
		"OTEL_METRICS_EXPORTER=none",
		"OTEL_LOGS_EXPORTER=none",
	} {
		if !strings.Contains(claudeBranch, want) {
			t.Fatalf("claude branch missing %q\n---\n%s", want, claudeBranch)
		}
	}
	for _, forbidden := range []string{
		".claude/settings.json",
		`ANTHROPIC_BASE_URL"`,
	} {
		if strings.Contains(claudeBranch, forbidden) {
			t.Fatalf("claude branch must not contain %q\n---\n%s", forbidden, claudeBranch)
		}
	}
}

func TestSetupScriptRespectsEditableGatewayRuntimeOptions(t *testing.T) {
	script := buildCodexConfigScript("https://pool.example/", "cap_abc123", "gpt-5.5", "", "", "", CodexSetupScriptOptions{
		StrictLinuxDefault:     false,
		DisableNonessentialEnv: false,
	})

	claudeBranch := scriptBetween(t, script, "configure_claude() {", "\n}\n\nmain()")
	if !strings.Contains(claudeBranch, `POOL_STRICT_LINUX="${POOL_STRICT_LINUX:-0}"`) {
		t.Fatalf("claude branch should use editable strict default 0\n---\n%s", claudeBranch)
	}
	for _, forbidden := range []string{
		"CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1",
		"DO_NOT_TRACK=1",
		"DISABLE_TELEMETRY=1",
		"DISABLE_ERROR_REPORTING=1",
		"DISABLE_AUTOUPDATER=1",
		"OTEL_METRICS_EXPORTER=none",
		"OTEL_LOGS_EXPORTER=none",
	} {
		if strings.Contains(claudeBranch, forbidden) {
			t.Fatalf("disable-nonessential env should be admin-editable and omitted when disabled; found %q\n---\n%s", forbidden, claudeBranch)
		}
	}
}

func TestSetupScriptCodexAutomationWritesOnlyCodexConfig(t *testing.T) {
	if _, err := exec.LookPath("bash"); err != nil {
		t.Skip("bash not available")
	}
	home := t.TempDir()
	script := buildCodexConfigScript("https://pool.example/", "cap_abc123", "gpt-5.5", "", "", "")
	p := filepath.Join(t.TempDir(), "setup.sh")
	if err := os.WriteFile(p, []byte(script), 0o700); err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command("bash", p)
	cmd.Env = []string{
		"HOME=" + home,
		"PATH=" + os.Getenv("PATH"),
		"POOL_CLIENT=codex",
		"POOL_INSTALL_RTK=0",
	}
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("codex automation failed: %v\n%s", err, out)
	}
	configPath := filepath.Join(home, ".codex", "config.toml")
	data, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("codex config missing: %v\noutput:\n%s", err, out)
	}
	config := string(data)
	for _, want := range []string{`model = "gpt-5.5"`, `base_url = "https://pool.example/v1"`, `wire_api = "responses"`, `experimental_bearer_token = "cap_abc123"`} {
		if !strings.Contains(config, want) {
			t.Fatalf("codex config missing %q\n---\n%s", want, config)
		}
	}
	for _, forbidden := range []string{".claude", ".claude-gateway"} {
		if _, err := os.Stat(filepath.Join(home, forbidden)); err == nil {
			t.Fatalf("codex branch created %s", forbidden)
		}
	}
}

func scriptBetween(t *testing.T, script, start, end string) string {
	t.Helper()
	i := strings.Index(script, start)
	if i < 0 {
		t.Fatalf("script missing start marker %q", start)
	}
	j := strings.Index(script[i:], end)
	if j < 0 {
		t.Fatalf("script missing end marker %q after %q", end, start)
	}
	return script[i : i+j]
}

func TestSetupScriptSanitizesModel(t *testing.T) {
	script := buildCodexConfigScript("https://pool.example/", "cap_abc123", "gpt-5\"\nmalicious = true", "", "", "")
	if strings.Contains(script, "MODEL=\"gpt-5\"\nmalicious") || strings.Contains(script, "\nmalicious = true") {
		t.Fatalf("model value was not sanitized:\n%s", script)
	}
	if !strings.Contains(script, `MODEL='gpt-5malicious = true'`) {
		t.Fatalf("sanitized model assignment missing:\n%s", script)
	}
	script = buildCodexConfigScript("https://pool.example/$(touch bad)", "cap_abc123", "gpt-5`touch bad`", "", "", "")
	if strings.Contains(script, "ORIGIN=\"") || strings.Contains(script, "MODEL=\"") {
		t.Fatalf("shell assignments must use single-quoted literals:\n%s", script)
	}
}
