// cmd/decode-secrets/main.go decodes the operator's base64(UTF-16LE) credential env vars
// (yescapt_api, smsbower_API) into plaintext, and parses CLIPROXY_API
// (hostname:port:username:password) into the structured egress-profile fields the pool
// server + Node registrar consume. It writes a 0600 secrets file (never stdout) that the
// launch script sources, and emits a JSON object the pool admin API can ingest.
//
// Usage:
//
//	decode-secrets -out .run/secrets.env        # writes KEY=VALUE shell exports
//	decode-secrets -json .run/secrets.json       # writes structured JSON for the API
//
// The plaintext never touches the model context — only the on-disk file.
package main

import (
	"encoding/base64"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"strings"
)

// b64UTF16 decodes a base64(UTF-16LE) blob to a plaintext string.
func b64UTF16(s string) (string, error) {
	raw, err := base64.StdEncoding.DecodeString(strings.TrimSpace(s))
	if err != nil {
		// Tolerate URL-safe base64 too.
		raw, err = base64.URLEncoding.DecodeString(strings.TrimSpace(s))
		if err != nil {
			return "", err
		}
	}
	// UTF-16LE: every other byte. If it's already plain ASCII (no nulls), return as-is.
	if !hasNull(raw) {
		return string(raw), nil
	}
	// Decode UTF-16LE (strip the BOM if present).
	runes := make([]rune, 0, len(raw)/2)
	for i := 0; i+1 < len(raw); i += 2 {
		r := rune(uint16(raw[i]) | uint16(raw[i+1])<<8)
		if r == 0xFEFF { // BOM
			continue
		}
		runes = append(runes, r)
	}
	return string(runes), nil
}

func hasNull(b []byte) bool {
	for _, v := range b {
		if v == 0 {
			return true
		}
	}
	return false
}

// cliproxyParts parses "host:port:user:pass" into its four fields.
func cliproxyParts(s string) (host, port, user, pass string, err error) {
	parts := strings.SplitN(strings.TrimSpace(s), ":", 4)
	if len(parts) != 4 {
		return "", "", "", "", fmt.Errorf("CLIPROXY_API must be host:port:user:pass (got %d fields)", len(parts))
	}
	return parts[0], parts[1], parts[2], parts[3], nil
}

type secrets struct {
	YesCaptchaAPI string `json:"yescaptcha_api,omitempty"`
	SMSBowerAPI   string `json:"smsbower_api,omitempty"`
	Cliproxy      struct {
		Host string `json:"host"`
		Port string `json:"port"`
		User string `json:"user"`
		Pass string `json:"pass"`
		// Full http_proxy URL the egress profile + Node registrar consume.
		URL string `json:"url"`
		// APIKey is the cliproxy account API token used by the api_whitelist proxy mode
		// (call api.cliproxy.io/white/api to extract ip:port). Decoded from CLIPROXY_API_KEY
		// (which may be base64(UTF-16LE) like the other creds, or plain ASCII).
		APIKey string `json:"api_key,omitempty"`
	} `json:"cliproxy"`
}

func main() {
	outShell := flag.String("out", "", "write shell-export file to this path (0600)")
	outJSON := flag.String("json", "", "write structured JSON to this path (0600)")
	flag.Parse()

	var sec secrets
	var errs []string

	if v := os.Getenv("yescapt_api"); v != "" {
		d, err := b64UTF16(v)
		if err != nil {
			errs = append(errs, fmt.Sprintf("yescapt_api: %v", err))
		} else {
			sec.YesCaptchaAPI = strings.TrimSpace(d)
		}
	}
	if v := os.Getenv("smsbower_API"); v != "" {
		d, err := b64UTF16(v)
		if err != nil {
			errs = append(errs, fmt.Sprintf("smsbower_API: %v", err))
		} else {
			sec.SMSBowerAPI = strings.TrimSpace(d)
		}
	}
	if v := os.Getenv("CLIPROXY_API"); v != "" {
		host, port, user, pass, err := cliproxyParts(v)
		if err != nil {
			errs = append(errs, err.Error())
		} else {
			sec.Cliproxy.Host = host
			sec.Cliproxy.Port = port
			sec.Cliproxy.User = user
			sec.Cliproxy.Pass = pass
			sec.Cliproxy.URL = fmt.Sprintf("http://%s:%s@%s:%s", user, pass, host, port)
		}
	}

	if v := os.Getenv("CLIPROXY_API_KEY"); v != "" {
			d, err := b64UTF16(v)
			if err != nil {
				// CLIPROXY_API_KEY might be plain ASCII (not base64-encoded); try raw.
				sec.Cliproxy.APIKey = strings.TrimSpace(v)
			} else {
				sec.Cliproxy.APIKey = strings.TrimSpace(d)
			}
		}
		if *outJSON != "" {
		raw, _ := json.MarshalIndent(sec, "", "  ")
		if err := os.WriteFile(*outJSON, raw, 0o600); err != nil {
			fmt.Fprintln(os.Stderr, "write json:", err)
			os.Exit(1)
		}
	}
	if *outShell != "" {
		var b strings.Builder
		fmt.Fprintf(&b, "# auto-generated by decode-secrets — plaintext credentials, chmod 0600, do NOT commit\n")
		if sec.YesCaptchaAPI != "" {
			fmt.Fprintf(&b, "export YESCAPTCHA_API=%q\n", sec.YesCaptchaAPI)
		}
		if sec.SMSBowerAPI != "" {
			fmt.Fprintf(&b, "export SMSBOWER_API=%q\n", sec.SMSBowerAPI)
		}
		if sec.Cliproxy.Host != "" {
			fmt.Fprintf(&b, "export CLIPROXY_HOST=%q\n", sec.Cliproxy.Host)
			fmt.Fprintf(&b, "export CLIPROXY_PORT=%q\n", sec.Cliproxy.Port)
			fmt.Fprintf(&b, "export CLIPROXY_USER=%q\n", sec.Cliproxy.User)
			fmt.Fprintf(&b, "export CLIPROXY_PASS=%q\n", sec.Cliproxy.Pass)
			fmt.Fprintf(&b, "export CLIPROXY_URL=%q\n", sec.Cliproxy.URL)
		}
		if sec.Cliproxy.APIKey != "" {
			fmt.Fprintf(&b, "export CLIPROXY_API_KEY=%q\n", sec.Cliproxy.APIKey)
		}
		if err := os.WriteFile(*outShell, []byte(b.String()), 0o600); err != nil {
			fmt.Fprintln(os.Stderr, "write shell:", err)
			os.Exit(1)
		}
	}

	// Status to stdout (NO secrets — only presence + lengths for sanity).
	fmt.Printf("decoded: yescaptcha=%t smsbower=%t cliproxy=%t\n",
		sec.YesCaptchaAPI != "", sec.SMSBowerAPI != "", sec.Cliproxy.Host != "")
	if len(errs) > 0 {
		fmt.Fprintln(os.Stderr, "errors:")
		for _, e := range errs {
			fmt.Fprintln(os.Stderr, "  -", e)
		}
		os.Exit(2)
	}
}
