package api

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// TestSetupScriptBashSyntaxAndContents guards the one-click setup script generated by
// buildCodexConfigScript: it must offer the client/RTK choices, keep Codex and Claude
// configuration separated, wire Claude through gateway run-claude, and be valid bash.
func TestSetupScriptBashSyntaxAndContents(t *testing.T) {
	script := buildCodexConfigScript("https://pool.example/", "cap_abc123", "gpt-5.5", "xhigh", "never", "danger-full-access")
	for _, want := range []string{
		"POOL_CLIENT",      // automation override
		"POOL_INSTALL_RTK", // automation override
		"POOL_CLIENT_RUNTIME",
		"POOL_STRICT_LINUX", // legacy gateway runtime flag derived from client runtime
		"--client-runtime",
		"--doctor-only",
		"ADMIN_TOKEN",
		"select_client",
		"configure_codex",
		"configure_claude",
		"$GATEWAY_BIN run-claude --",
		"CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY",
		"CLAUDE_CODE_ENABLE_FINE_GRAINED_TOOL_STREAMING",
		`GATEWAY_KEY="${API_KEY:-any-non-empty}"`,
		`export ANTHROPIC_AUTH_TOKEN="$GATEWAY_KEY"`,
		`--key "$GATEWAY_KEY"`,
		`MODEL='gpt-5.5'`, // model via shell var → config.toml
		`model_reasoning_effort = "xhigh"`,
		`approval_policy = "never"`, // auto-approve all
		`sandbox_mode = "danger-full-access"`,
		`experimental_bearer_token = "$API_KEY"`,
	} {
		if !strings.Contains(script, want) {
			t.Fatalf("setup script missing %q", want)
		}
	}
	// Blanked-out behavior values must be omitted from the TOML (operator can dial
	// back). The help-text echoes still mention the words, so check the assignment form.
	bare := buildCodexConfigScript("https://pool.example/", "cap_abc123", "gpt-5.5", "", "", "")
	for _, line := range []string{`approval_policy = "`, `sandbox_mode = "`, `model_reasoning_effort = "`, `goals = true`} {
		if strings.Contains(bare, line) {
			t.Fatalf("empty behavior values should omit %q from config", line)
		}
	}
	if _, err := exec.LookPath("bash"); err != nil {
		t.Skip("bash not available")
	}
	p := filepath.Join(t.TempDir(), "setup.sh")
	if err := os.WriteFile(p, []byte(script), 0o600); err != nil {
		t.Fatal(err)
	}
	if out, err := exec.Command("bash", "-n", p).CombinedOutput(); err != nil {
		t.Fatalf("generated setup script has bash syntax errors: %v\n%s", err, out)
	}
}

func TestSetupScriptCodexUsesOnlyRequestedConfigurationAllowlist(t *testing.T) {
	script := buildCodexConfigScript("https://pool.example/", "cap_abc123", "gpt-5.6-sol", "ultra", "never", "danger-full-access")
	for _, want := range []string{
		`model_reasoning_effort = "ultra"`,
		`name = "OpenAI"`,
		`experimental_bearer_token = "$API_KEY"`,
	} {
		if !strings.Contains(script, want) {
			t.Fatalf("5.6 setup script missing %q\n---\n%s", want, script)
		}
	}
	codexBranch := scriptBetween(t, script, "configure_codex() {", "\n}\n\nGATEWAY_BIN=")
	for _, forbidden := range []string{
		"model_context_window =",
		"model_auto_compact_token_limit =",
		"supports_websockets =",
		"pool-token",
		"pool-client-id",
		"X-Pool-Client-ID",
		"[model_providers.$PROVIDER_ID.auth]",
		`command = "/bin/cat"`,
		"models_cache.json",
		"rtk ",
	} {
		if strings.Contains(codexBranch, forbidden) {
			t.Fatalf("Codex branch exceeded its configuration allowlist with %q\n---\n%s", forbidden, codexBranch)
		}
	}
	legacy := buildCodexConfigScript("https://pool.example/", "cap_abc123", "gpt-5.5", "xhigh", "never", "danger-full-access")
	for _, forbidden := range []string{"model_context_window =", "model_auto_compact_token_limit ="} {
		if strings.Contains(legacy, forbidden) {
			t.Fatalf("non-5.6 setup script received a static context override %q", forbidden)
		}
	}
}

func TestSetupScriptPreservesUnrelatedConfigAndSetsAPIKey(t *testing.T) {
	if _, err := exec.LookPath("bash"); err != nil {
		t.Skip("bash not available")
	}
	home := t.TempDir()
	codexDir := filepath.Join(home, ".codex")
	if err := os.MkdirAll(codexDir, 0o700); err != nil {
		t.Fatal(err)
	}
	existing := "model_context_window = 111000\nmodel_auto_compact_token_limit = 100000\n[features]\nmulti_agent = true\n"
	if err := os.WriteFile(filepath.Join(codexDir, "config.toml"), []byte(existing), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(codexDir, "models_cache.json"), []byte(`{"provider":"old"}`), 0o600); err != nil {
		t.Fatal(err)
	}
	scriptPath := filepath.Join(t.TempDir(), "setup.sh")
	if err := os.WriteFile(scriptPath, []byte(buildCodexConfigScript("https://pool.example/", "cap_abc123", "gpt-5.6-sol", "ultra", "never", "danger-full-access")), 0o700); err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command("bash", scriptPath)
	cmd.Env = []string{
		"HOME=" + home,
		"PATH=" + os.Getenv("PATH"),
		"POOL_CLIENT=codex",
	}
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("5.6 setup failed: %v\n%s", err, out)
	}
	data, err := os.ReadFile(filepath.Join(codexDir, "config.toml"))
	if err != nil {
		t.Fatal(err)
	}
	config := string(data)
	for _, line := range []string{
		`name = "OpenAI"`,
		`experimental_bearer_token = "cap_abc123"`,
	} {
		if strings.Count(config, line) != 1 {
			t.Fatalf("installed config must contain exactly one %q\n---\n%s", line, config)
		}
	}
	for _, preserved := range []string{"model_context_window = 111000", "model_auto_compact_token_limit = 100000"} {
		if strings.Count(config, preserved) != 1 {
			t.Fatalf("installer touched unrelated existing config %q\n---\n%s", preserved, config)
		}
	}
	for _, extraClientConfig := range []string{"X-Pool-Client-ID", "pool-client-id"} {
		if strings.Contains(config, extraClientConfig) {
			t.Fatalf("Codex must require only URL and API key; found extra client identity config %q\n---\n%s", extraClientConfig, config)
		}
	}
	if !strings.Contains(config, "multi_agent = true") || !strings.Contains(config, `model_reasoning_effort = "ultra"`) {
		t.Fatalf("setup reduced existing features or reasoning effort\n---\n%s", config)
	}
	if strings.Contains(config, `goals = true`) {
		t.Fatalf("setup invented a client-owned feature flag\n---\n%s", config)
	}
	firstTable := strings.Index(config, "[")
	for _, rootKey := range []string{`model = "gpt-5.6-sol"`, `model_provider = "poolserver"`, `model_reasoning_effort = "ultra"`} {
		pos := strings.Index(config, rootKey)
		if pos < 0 || firstTable < 0 || pos > firstTable {
			t.Fatalf("managed TOML root key %q was nested below a table\n---\n%s", rootKey, config)
		}
	}
	if providerPos, featuresPos := strings.Index(config, "[model_providers.poolserver]"), strings.Index(config, "[features]"); providerPos <= featuresPos {
		t.Fatalf("Pool provider replacement should follow preserved user tables without nesting root keys\n---\n%s", config)
	}
	if raw, err := os.ReadFile(filepath.Join(codexDir, "models_cache.json")); err != nil || string(raw) != `{"provider":"old"}` {
		t.Fatalf("installer modified unrelated model cache: raw=%q err=%v", raw, err)
	}
	if _, err := os.Stat(filepath.Join(codexDir, "pool-token")); !os.IsNotExist(err) {
		t.Fatalf("Codex branch created an extra token file: %v", err)
	}
}

func TestSetupScriptPreservesContextOverridesForEveryModel(t *testing.T) {
	if _, err := exec.LookPath("bash"); err != nil {
		t.Skip("bash not available")
	}
	home := t.TempDir()
	codexDir := filepath.Join(home, ".codex")
	if err := os.MkdirAll(codexDir, 0o700); err != nil {
		t.Fatal(err)
	}
	existing := "model_context_window = 256000\nmodel_auto_compact_token_limit = 220000\n[features]\nmulti_agent = true\n"
	if err := os.WriteFile(filepath.Join(codexDir, "config.toml"), []byte(existing), 0o600); err != nil {
		t.Fatal(err)
	}
	scriptPath := filepath.Join(t.TempDir(), "setup.sh")
	if err := os.WriteFile(scriptPath, []byte(buildCodexConfigScript("https://pool.example/", "cap_abc123", "gpt-5.5", "xhigh", "never", "danger-full-access")), 0o700); err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command("bash", scriptPath)
	cmd.Env = []string{
		"HOME=" + home,
		"PATH=" + os.Getenv("PATH"),
		"POOL_CLIENT=codex",
	}
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("non-5.6 setup failed: %v\n%s", err, out)
	}
	data, err := os.ReadFile(filepath.Join(codexDir, "config.toml"))
	if err != nil {
		t.Fatal(err)
	}
	config := string(data)
	for _, preserved := range []string{"model_context_window = 256000", "model_auto_compact_token_limit = 220000"} {
		if strings.Count(config, preserved) != 1 {
			t.Fatalf("non-5.6 setup touched unrelated override %q\n---\n%s", preserved, config)
		}
	}
	if strings.Count(config, "multi_agent = true") != 1 {
		t.Fatalf("non-context user config was not preserved exactly once\n---\n%s", config)
	}
}

func TestSetupScriptRefusesSymlinkedCodexConfig(t *testing.T) {
	if _, err := exec.LookPath("bash"); err != nil {
		t.Skip("bash not available")
	}
	home := t.TempDir()
	codexDir := filepath.Join(home, ".codex")
	if err := os.MkdirAll(codexDir, 0o700); err != nil {
		t.Fatal(err)
	}
	outside := filepath.Join(t.TempDir(), "must-not-change")
	if err := os.WriteFile(outside, []byte("original\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(outside, filepath.Join(codexDir, "config.toml")); err != nil {
		t.Fatal(err)
	}
	scriptPath := filepath.Join(t.TempDir(), "setup.sh")
	if err := os.WriteFile(scriptPath, []byte(buildCodexConfigScript("https://pool.example/", "replacement-secret", "gpt-5.6-sol", "ultra", "never", "danger-full-access")), 0o700); err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command("bash", scriptPath)
	cmd.Env = []string{
		"HOME=" + home,
		"PATH=" + os.Getenv("PATH"),
		"POOL_CLIENT=codex",
	}
	if out, err := cmd.CombinedOutput(); err == nil || !strings.Contains(string(out), "symlinked") {
		t.Fatalf("symlinked config was not rejected: err=%v output=%s", err, out)
	}
	if raw, err := os.ReadFile(outside); err != nil || string(raw) != "original\n" {
		t.Fatalf("symlink target changed: raw=%q err=%v", raw, err)
	}
}

func TestSetupScriptCodexBranchIsIsolatedFromClaudeGateway(t *testing.T) {
	script := buildCodexConfigScript("https://pool.example/", "cap_abc123", "gpt-5.5", "", "", "")

	codexBranch := scriptBetween(t, script, "configure_codex() {", "\n}\n\nGATEWAY_BIN=")
	for _, want := range []string{
		`CONFIG="$CODEX_HOME/config.toml"`,
		`base_url = "$ORIGIN/v1"`,
		`wire_api = "responses"`,
		`experimental_bearer_token = "$API_KEY"`,
	} {
		if !strings.Contains(codexBranch, want) {
			t.Fatalf("codex branch missing %q\n---\n%s", want, codexBranch)
		}
	}
	for _, forbidden := range []string{
		"gateway run-claude",
		".claude/settings.json",
		"ANTHROPIC_BASE_URL",
		"install-wrapper",
		"supports_websockets",
		"pool-token",
		"models_cache.json",
		"rtk ",
		`goals = true`,
	} {
		if strings.Contains(codexBranch, forbidden) {
			t.Fatalf("codex branch must not contain %q\n---\n%s", forbidden, codexBranch)
		}
	}
}

func TestSetupScriptClaudeBranchUsesGatewayCompatRuntimeByDefault(t *testing.T) {
	script := buildCodexConfigScript("https://pool.example/", "cap_abc123", "gpt-5.5", "", "", "")

	claudeBranch := scriptBetween(t, script, "configure_claude() {", "\n}\n\nmain()")
	for _, want := range []string{
		"install_gateway_binary",
		`"$GATEWAY_BIN" init --pool-url "$ORIGIN" --key "$GATEWAY_KEY"`,
		`Claude Code 模型由客户端自行选择；VPS force_model 可能在服务端覆盖`,
		`"$GATEWAY_BIN" stop`,
		`CA 自动信任失败；安装尚未完成`,
		`"$GATEWAY_BIN" start-background`,
		`"$GATEWAY_BIN" probe-identity`,
		"$GATEWAY_BIN run-claude --",
		"ANTHROPIC_BASE_URL=$ORIGIN",
		"unset ANTHROPIC_API_KEY",
		`ANTHROPIC_AUTH_TOKEN="$GATEWAY_KEY"`,
		"CLAUDE_CODE_ENABLE_AUTO_MODE=1",
		"CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY=1",
		"CLAUDE_CODE_ENABLE_FINE_GRAINED_TOOL_STREAMING=1",
		"claude-plan",
		`POOL_CLIENT_RUNTIME="${POOL_CLIENT_RUNTIME:-compat}"`,
		`POOL_STRICT_LINUX="${POOL_STRICT_LINUX:-0}"`,
	} {
		if !strings.Contains(claudeBranch, want) {
			t.Fatalf("claude branch missing %q\n---\n%s", want, claudeBranch)
		}
	}
	for _, forbidden := range []string{
		".claude/settings.json",
		`--model "$MODEL"`,
		"ANTHROPIC_MODEL",
		"CLAUDE_CODE_SUBAGENT_MODEL",
		"CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1",
	} {
		if strings.Contains(claudeBranch, forbidden) {
			t.Fatalf("claude branch must not contain %q\n---\n%s", forbidden, claudeBranch)
		}
	}
}

func TestSetupScriptGatewayInstallerLeavesGatewayOnPath(t *testing.T) {
	script := buildCodexConfigScript("https://pool.example/", "cap_abc123", "gpt-5.5", "", "", "")
	installer := scriptBetween(t, script, "install_gateway_binary() {", "\n}\n\nconfigure_claude()")
	for _, want := range []string{
		`existing_gateway="$(command -v gateway 2>/dev/null || true)"`,
		`"$existing_gateway" stop || true`,
		`if [ -n "$existing_gateway" ] && [ -w "$existing_gateway" ]`,
		`if [ "$(id -u)" = "0" ]`,
		`target="/usr/local/bin/gateway"`,
		`target="$HOME/.local/bin/gateway"`,
		`ensure_user_local_bin_on_path`,
	} {
		if !strings.Contains(installer, want) {
			t.Fatalf("gateway installer should persist gateway on PATH; missing %q\n---\n%s", want, installer)
		}
	}
	if strings.Contains(installer, `if GATEWAY_BIN="$(command -v gateway 2>/dev/null)"; then`) {
		t.Fatalf("gateway installer must not skip downloading a newer binary when gateway already exists\n---\n%s", installer)
	}
}

func TestSetupScriptRespectsEditableGatewayRuntimeOptions(t *testing.T) {
	script := buildCodexConfigScript("https://pool.example/", "cap_abc123", "gpt-5.5", "", "", "", CodexSetupScriptOptions{
		StrictLinuxDefault:     false,
		DisableNonessentialEnv: false,
	})

	claudeBranch := scriptBetween(t, script, "configure_claude() {", "\n}\n\nmain()")
	if !strings.Contains(claudeBranch, `POOL_CLIENT_RUNTIME="${POOL_CLIENT_RUNTIME:-compat}"`) {
		t.Fatalf("claude branch should use editable runtime default compat\n---\n%s", claudeBranch)
	}
	if !strings.Contains(claudeBranch, `POOL_STRICT_LINUX="${POOL_STRICT_LINUX:-0}"`) {
		t.Fatalf("claude branch should use editable strict default 0\n---\n%s", claudeBranch)
	}
	for _, forbidden := range []string{
		"CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1",
		"DO_NOT_TRACK=1",
		"DISABLE_TELEMETRY=1",
		"DISABLE_ERROR_REPORTING=1",
		"DISABLE_AUTOUPDATER=1",
		"OTEL_METRICS_EXPORTER=none",
		"OTEL_LOGS_EXPORTER=none",
	} {
		if strings.Contains(claudeBranch, forbidden) {
			t.Fatalf("disable-nonessential env should be admin-editable and omitted when disabled; found %q\n---\n%s", forbidden, claudeBranch)
		}
	}
}

func TestSetupScriptCanDefaultClaudeStrictRuntime(t *testing.T) {
	script := buildCodexConfigScript("https://pool.example/", "cap_abc123", "gpt-5.5", "", "", "", CodexSetupScriptOptions{
		StrictLinuxDefault:     true,
		DisableNonessentialEnv: true,
	})
	if !strings.Contains(script, `POOL_CLIENT_RUNTIME="${POOL_CLIENT_RUNTIME:-strict}"`) {
		t.Fatalf("strict option should default POOL_CLIENT_RUNTIME=strict\n---\n%s", script)
	}
	if !strings.Contains(script, `POOL_STRICT_LINUX="${POOL_STRICT_LINUX:-1}"`) {
		t.Fatalf("strict option should default POOL_STRICT_LINUX=1\n---\n%s", script)
	}
}

func TestSetupScriptCodexAutomationWritesOnlyCodexConfig(t *testing.T) {
	if _, err := exec.LookPath("bash"); err != nil {
		t.Skip("bash not available")
	}
	home := t.TempDir()
	script := buildCodexConfigScript("https://pool.example/", "cap_abc123", "gpt-5.5", "", "", "")
	p := filepath.Join(t.TempDir(), "setup.sh")
	if err := os.WriteFile(p, []byte(script), 0o700); err != nil {
		t.Fatal(err)
	}
	codexDir := filepath.Join(home, ".codex")
	if err := os.MkdirAll(codexDir, 0o700); err != nil {
		t.Fatal(err)
	}
	existing := `[mcp_servers.keep]
command = "keep-mcp"

[plugins.keep]
path = "/opt/codex/plugins/keep"
skill = "repo-review"

[features]
multi_agent = true

[model_providers.other]
name = "Other"
base_url = "https://other.example/v1"
`
	if err := os.WriteFile(filepath.Join(codexDir, "config.toml"), []byte(existing), 0o600); err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command("bash", p)
	cmd.Env = []string{
		"HOME=" + home,
		"PATH=" + os.Getenv("PATH"),
		"POOL_CLIENT=codex",
	}
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("codex automation failed: %v\n%s", err, out)
	}
	configPath := filepath.Join(home, ".codex", "config.toml")
	data, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("codex config missing: %v\noutput:\n%s", err, out)
	}
	config := string(data)
	for _, want := range []string{
		`model = "gpt-5.5"`,
		`base_url = "https://pool.example/v1"`,
		`wire_api = "responses"`,
		`experimental_bearer_token = "cap_abc123"`,
	} {
		if !strings.Contains(config, want) {
			t.Fatalf("codex config missing %q\n---\n%s", want, config)
		}
	}
	if _, err := os.Stat(filepath.Join(codexDir, "pool-token")); !os.IsNotExist(err) {
		t.Fatalf("Codex branch created an extra credential file: %v", err)
	}
	for _, want := range []string{`[mcp_servers.keep]`, `command = "keep-mcp"`, `[plugins.keep]`, `skill = "repo-review"`, `[features]`, `multi_agent = true`, `[model_providers.other]`} {
		if !strings.Contains(config, want) {
			t.Fatalf("codex config merge dropped existing %q\n---\n%s", want, config)
		}
	}
	for _, forbidden := range []string{".claude", ".claude-gateway"} {
		if _, err := os.Stat(filepath.Join(home, forbidden)); err == nil {
			t.Fatalf("codex branch created %s", forbidden)
		}
	}
}

func TestSetupScriptMinimalCodexConfigParsesWithInstalledCLI(t *testing.T) {
	codex, err := exec.LookPath("codex")
	if err != nil {
		t.Skip("codex CLI not installed")
	}
	home := t.TempDir()
	scriptPath := filepath.Join(t.TempDir(), "setup.sh")
	options := defaultCodexSetupScriptOptions()
	options.CodexOnly = true
	script := buildCodexConfigScript("https://pool.example/", "cap_parser_test", "gpt-5.6-sol", "ultra", "never", "danger-full-access", options)
	if err := os.WriteFile(scriptPath, []byte(script), 0o700); err != nil {
		t.Fatal(err)
	}
	setup := exec.Command("bash", scriptPath)
	setup.Env = []string{
		"HOME=" + home,
		"PATH=" + os.Getenv("PATH"),
	}
	if out, err := setup.CombinedOutput(); err != nil {
		t.Fatalf("minimal Codex setup failed: %v\n%s", err, out)
	}
	check := exec.Command(codex, "features", "list")
	check.Env = append(os.Environ(), "HOME="+home, "CODEX_HOME="+filepath.Join(home, ".codex"))
	out, err := check.CombinedOutput()
	if err != nil {
		t.Fatalf("installed Codex rejected generated config: %v\n%s", err, out)
	}
	if strings.Contains(script, `goals = true`) {
		t.Fatalf("fresh setup must not enable a client-owned feature flag:\n%s", script)
	}
	_ = out
}

func scriptBetween(t *testing.T, script, start, end string) string {
	t.Helper()
	i := strings.Index(script, start)
	if i < 0 {
		t.Fatalf("script missing start marker %q", start)
	}
	j := strings.Index(script[i:], end)
	if j < 0 {
		t.Fatalf("script missing end marker %q after %q", end, start)
	}
	return script[i : i+j]
}

func TestSetupScriptSanitizesModel(t *testing.T) {
	script := buildCodexConfigScript("https://pool.example/", "cap_abc123", "gpt-5\"\nmalicious = true", "", "", "")
	if strings.Contains(script, "MODEL=\"gpt-5\"\nmalicious") || strings.Contains(script, "\nmalicious = true") {
		t.Fatalf("model value was not sanitized:\n%s", script)
	}
	if !strings.Contains(script, `MODEL='gpt-5malicious = true'`) {
		t.Fatalf("sanitized model assignment missing:\n%s", script)
	}
	script = buildCodexConfigScript("https://pool.example/$(touch bad)", "cap_abc123", "gpt-5`touch bad`", "", "", "")
	if strings.Contains(script, "ORIGIN=\"") || strings.Contains(script, "MODEL=\"") {
		t.Fatalf("shell assignments must use single-quoted literals:\n%s", script)
	}
}
